CREATE OR REPLACE FORCE EDITIONABLE VIEW "RODRIGO"."DESC_OPERACOES_V" ("ID_OPERACAO", "ID_OPERACAO_PAR", "TIPO_OPERACAO", "NM_OPERADORA", "DESC_FATURA", "VENCIMENTO", "DT_OPERACAO", "DT_OPERACAO_UNICA", "NM_USUARIO", "NM_CATEGORIA", "NM_SUB_CATEGORIA", "PARCELA_ATUAL", "PARCELA_TOTAL", "TP_RESPONSAVEL", "VL_OPERACAO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    O.ID_OPERACAO,
    O.ID_OPERACAO_PAR,
    O.TIPO_OPERACAO,
    OP.NM_OPERADORA,
    F.DESC_FATURA,
    F.VENCIMENTO,
    O.DT_OPERACAO,
    DECODE(O.TIPO_OPERACAO, 'DÉBITO', O.DT_OPERACAO, F.VENCIMENTO) DT_OPERACAO_UNICA,
    U.NM_USUARIO,
    C.NM_CATEGORIA,
    C.NM_SUB_CATEGORIA,
    O.PARCELA_ATUAL,
    O.PARCELA_TOTAL,
    O.TP_RESPONSAVEL,
    O.VL_OPERACAO
FROM
         OPERACOES O
    JOIN CATEGORIAS C ON C.ID_CATEGORIA = O.ID_CATEGORIA
    LEFT JOIN FATURAS    F ON F.ID_FATURA = O.ID_FATURA
    LEFT JOIN OPERADORAS OP ON OP.ID_OPERADORA = O.ID_OPERADORA
    LEFT JOIN USUARIOS   U ON U.ID_USUARIO = O.ID_USUARIO
ORDER BY
    O.PARCELA_ATUAL,
    8 DESC,
    O.DT_OPERACAO DESC,
    O.ID_OPERACAO DESC
;

