CREATE OR REPLACE VIEW RODRIGO.DESC_OPERACOES_V AS 
  SELECT
    O.ID_OPERACAO,
    O.ID_OPERACAO_PAR,
    O.TIPO_OPERACAO,
    OP.ID_OPERADORA,
    OP.NM_OPERADORA,
    F.ID_FATURA,
    F.DESC_FATURA,
    F.VENCIMENTO,
    O.DT_OPERACAO,
    DECODE(O.TIPO_OPERACAO, 'DÉBITO', O.DT_OPERACAO, F.VENCIMENTO) DT_OPERACAO_UNICA,
    ADD_MONTHS(O.DT_OPERACAO,(O.PARCELA_ATUAL - 1)*-1) DT_OPERACAO_ORI,
    U.ID_USUARIO,
    U.NM_USUARIO,
    C.ID_CATEGORIA,
    C.NM_CATEGORIA,
    C.NM_SUB_CATEGORIA,
    O.PARCELA_ATUAL,
    O.PARCELA_TOTAL,
    O.PARCELA_ATUAL || '/' || O.PARCELA_TOTAL PARCELA,
    O.TP_RESPONSAVEL,
    O.VL_OPERACAO
FROM
         OPERACOES O
    JOIN CATEGORIAS C ON C.ID_CATEGORIA = O.ID_CATEGORIA
    LEFT JOIN FATURAS    F ON F.ID_FATURA = O.ID_FATURA
    LEFT JOIN OPERADORAS OP ON OP.ID_OPERADORA = O.ID_OPERADORA
    LEFT JOIN USUARIOS   U ON U.ID_USUARIO = O.ID_USUARIO
ORDER BY
    ADD_MONTHS(O.DT_OPERACAO,(O.PARCELA_ATUAL - 1)*-1) DESC
;