CREATE OR REPLACE VIEW RODRIGO.DESC_OPERACOES_PARC_V AS 
  WITH OPE AS (
    SELECT
        CASE
            WHEN D.PARCELA_ATUAL > 1 THEN
                D.ID_OPERACAO_PAR
            ELSE
                D.ID_OPERACAO
        END ID_OPERACAO_UNI,
        D.ID_OPERACAO,
        D.TIPO_OPERACAO,
        D.ID_OPERADORA,
        D.NM_OPERADORA,
        D.ID_FATURA,
        D.DESC_FATURA,
        D.DT_OPERACAO,
        D.DT_OPERACAO_UNICA,
        D.DT_OPERACAO_ORI,
        D.ID_USUARIO,
        D.NM_USUARIO,
        D.ID_CATEGORIA,
        D.NM_CATEGORIA,
        D.NM_SUB_CATEGORIA,
        D.PARCELA_ATUAL,
        D.PARCELA_TOTAL,
        D.TP_RESPONSAVEL,
        D.VL_OPERACAO
    FROM
        DESC_OPERACOES_V D
    WHERE
        D.TIPO_OPERACAO = 'CRÉDITO'
)
SELECT
    *
FROM
    OPE
;

