CREATE OR REPLACE FORCE EDITIONABLE VIEW "RODRIGO"."DESC_OPERACOES_PARC_V" ("ID_OPERACAO_UNI", "ID_OPERACAO", "TIPO_OPERACAO", "NM_OPERADORA", "DESC_FATURA", "DT_OPERACAO", "NM_USUARIO", "NM_CATEGORIA", "NM_SUB_CATEGORIA", "PARCELA_ATUAL", "PARCELA_TOTAL", "TP_RESPONSAVEL", "VL_OPERACAO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH OPE AS (
    SELECT
        CASE
            WHEN D.PARCELA_ATUAL > 1 THEN
                D.ID_OPERACAO_PAR
            ELSE
                D.ID_OPERACAO
        END ID_OPERACAO_UNI,
        D.ID_OPERACAO,
        D.TIPO_OPERACAO,
        D.NM_OPERADORA,
        D.DESC_FATURA,
        D.DT_OPERACAO,
        D.NM_USUARIO,
        D.NM_CATEGORIA,
        D.NM_SUB_CATEGORIA,
        D.PARCELA_ATUAL,
        D.PARCELA_TOTAL,
        D.TP_RESPONSAVEL,
        D.VL_OPERACAO
    FROM
        DESC_OPERACOES_V D
    WHERE
        D.TIPO_OPERACAO = 'CRÉDITO'
)
SELECT
    "ID_OPERACAO_UNI","ID_OPERACAO","TIPO_OPERACAO","NM_OPERADORA","DESC_FATURA","DT_OPERACAO","NM_USUARIO","NM_CATEGORIA","NM_SUB_CATEGORIA","PARCELA_ATUAL","PARCELA_TOTAL","TP_RESPONSAVEL","VL_OPERACAO"
FROM
    OPE
;

