CREATE TABLE "RODRIGO"."OPERADORAS" 
   (	"ID_OPERADORA" NUMBER(*,0), 
	"NM_OPERADORA" VARCHAR2(10 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "RODRIGO"."PK_OPERADORAS" ON "RODRIGO"."OPERADORAS" ("ID_OPERADORA") 
  ;

ALTER TABLE "RODRIGO"."OPERADORAS" MODIFY ("ID_OPERADORA" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."OPERADORAS" MODIFY ("NM_OPERADORA" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."OPERADORAS" ADD CONSTRAINT "PK_OPERADORAS" PRIMARY KEY ("ID_OPERADORA")
  USING INDEX  ENABLE;

