CREATE TABLE "RODRIGO"."FATURAS" 
   (	"ID_FATURA" NUMBER(*,0), 
	"ID_OPERADORA" NUMBER(*,0), 
	"DESC_FATURA" VARCHAR2(7 BYTE) COLLATE "USING_NLS_COMP", 
	"INI_FATURA" DATE, 
	"FIM_FATURA" DATE, 
	"VENCIMENTO" DATE
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "RODRIGO"."PK_FATURAS" ON "RODRIGO"."FATURAS" ("ID_FATURA", "ID_OPERADORA") 
  ;

ALTER TABLE "RODRIGO"."FATURAS" MODIFY ("ID_FATURA" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."FATURAS" MODIFY ("ID_OPERADORA" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."FATURAS" MODIFY ("INI_FATURA" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."FATURAS" MODIFY ("FIM_FATURA" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."FATURAS" MODIFY ("VENCIMENTO" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."FATURAS" ADD CONSTRAINT "PK_FATURAS" PRIMARY KEY ("ID_FATURA", "ID_OPERADORA")
  USING INDEX  ENABLE;

ALTER TABLE "RODRIGO"."FATURAS" ADD CONSTRAINT "FK_OPERADORAS" FOREIGN KEY ("ID_OPERADORA")
	  REFERENCES "RODRIGO"."OPERADORAS" ("ID_OPERADORA") ENABLE;

