CREATE TABLE "RODRIGO"."USUARIOS" 
   (	"ID_USUARIO" NUMBER(*,0), 
	"NM_USUARIO" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "RODRIGO"."PK_USUARIOS" ON "RODRIGO"."USUARIOS" ("ID_USUARIO") 
  ;

ALTER TABLE "RODRIGO"."USUARIOS" MODIFY ("ID_USUARIO" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."USUARIOS" MODIFY ("NM_USUARIO" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."USUARIOS" ADD CONSTRAINT "PK_USUARIOS" PRIMARY KEY ("ID_USUARIO")
  USING INDEX  ENABLE;

