CREATE TABLE "RODRIGO"."OPERACOES" 
   (	"ID_OPERACAO" NUMBER(*,0), 
	"ID_OPERACAO_PAR" NUMBER(*,0), 
	"ID_FATURA" NUMBER(*,0), 
	"ID_OPERADORA" NUMBER(*,0), 
	"ID_USUARIO" NUMBER(*,0), 
	"ID_CATEGORIA" NUMBER(*,0), 
	"TIPO_OPERACAO" VARCHAR2(30 BYTE) COLLATE "USING_NLS_COMP", 
	"DT_OPERACAO" DATE, 
	"VL_OPERACAO" FLOAT(126), 
	"PARCELA_ATUAL" NUMBER(*,0), 
	"PARCELA_TOTAL" NUMBER(*,0), 
	"TP_RESPONSAVEL" CHAR(1 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

COMMENT ON COLUMN "RODRIGO"."OPERACOES"."ID_OPERACAO" IS 'ID da Operação';

COMMENT ON COLUMN "RODRIGO"."OPERACOES"."ID_OPERACAO_PAR" IS 'ID da Operação da Primeira Parcela';

COMMENT ON COLUMN "RODRIGO"."OPERACOES"."TIPO_OPERACAO" IS 'CRÉDITO ou DÉBITO';

COMMENT ON COLUMN "RODRIGO"."OPERACOES"."TP_RESPONSAVEL" IS 'R = Rodrigo, 
C = Cris, 
A = Ambos,';

CREATE INDEX "RODRIGO"."IDX_OPERACOES_USU" ON "RODRIGO"."OPERACOES" ("ID_USUARIO") 
  ;

CREATE UNIQUE INDEX "RODRIGO"."PK_OPERACOES" ON "RODRIGO"."OPERACOES" ("ID_OPERACAO") 
  ;

CREATE INDEX "RODRIGO"."IDX_OPERACOES_CAT" ON "RODRIGO"."OPERACOES" ("ID_CATEGORIA") 
  ;

CREATE INDEX "RODRIGO"."IDX_OPERACOES_FAT" ON "RODRIGO"."OPERACOES" ("ID_FATURA") 
  ;

ALTER TABLE "RODRIGO"."OPERACOES" ADD CONSTRAINT "PK_OPERACOES" PRIMARY KEY ("ID_OPERACAO")
  USING INDEX "RODRIGO"."PK_OPERACOES"  ENABLE;

ALTER TABLE "RODRIGO"."OPERACOES" MODIFY ("ID_OPERACAO" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."OPERACOES" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."OPERACOES" MODIFY ("TIPO_OPERACAO" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."OPERACOES" MODIFY ("DT_OPERACAO" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."OPERACOES" MODIFY ("VL_OPERACAO" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."OPERACOES" MODIFY ("TP_RESPONSAVEL" NOT NULL ENABLE);

ALTER TABLE "RODRIGO"."OPERACOES" ADD CHECK ( TP_RESPONSAVEL IN ('R','C','A')) ENABLE;

ALTER TABLE "RODRIGO"."OPERACOES" ADD CONSTRAINT "FK_CATEGORIAS" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "RODRIGO"."CATEGORIAS" ("ID_CATEGORIA") ENABLE;

ALTER TABLE "RODRIGO"."OPERACOES" ADD CONSTRAINT "FK_FATURAS" FOREIGN KEY ("ID_FATURA", "ID_OPERADORA")
	  REFERENCES "RODRIGO"."FATURAS" ("ID_FATURA", "ID_OPERADORA") ENABLE;

ALTER TABLE "RODRIGO"."OPERACOES" ADD CONSTRAINT "FK_USUARIOS" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "RODRIGO"."USUARIOS" ("ID_USUARIO") ENABLE;

